version: '3.7'
services:
  wiremock-service:
    image: wiremock/wiremock
    container_name: "wiremock-service"
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/stubs:/home/wiremock
    command: ["--verbose", "--global-response-templating", "--local-response-templating"]
